### ISSUE TITLE
make a pre compiled windows and linux bin

### ISSUE THREAD

**Issue by TheMKDev** [m-byte918/AgarOSS#11]

**Comment by m-byte918** [comment]
I would do this-- but the way the server is now, you would need to recompile the project each time you change a configuration in `Settings.cpp`, so having pre-compiled binaries would be pretty much useless.
 
There is a need to load configurations from a separate file that does not need to be compiled with the project. Once this is implemented, I will consider adding pre-compiled binaries ;)

**Comment by m-byte918** [comment]
Configurations are now loaded from a json file, and no longer require a recompiling of the project to change (see Settings.json in https://github.com/m-byte918/AgarOSS/commit/0eb0b7cab22dd20fc8000b35ede912d96bbbe829). 
About pre-compiled binaries: they may not work with every system because each binary is specific to the machine it was compiled on. Therefore I will not add them. 
However I have made it significantly easier to compile the project, you only need to run a single file to generate an executable. You can find the steps to do so in the README :)
